name: build windows

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up jdk 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: build tin
      run: .\gradlew.bat check --no-daemon

    - name: upload tinengine jar
      uses: actions/upload-artifact@v2.2.4
      with:
        name: TinEngine
        path: build/libs/TinEngine
        if-no-files-found: error

    - name: check tin
      run: .\gradlew.bat check --no-daemon

    - name: upload tinengine checkstyle
      uses: actions/upload-artifact@v2.2.4
      with:
        name: code results
        path: build/reports/checkstyle/main.html
        if-no-files-found: error

    - name: stop gradle
      run: .\gradlew.bat --stop
